### ISSUE TITLE
Ubuntu Linux Also ?

### ISSUE THREAD

**Issue by MonkeyChap** [sindresorhus/fix-path#10]
Hi

This module has been great for our application - many thanks !

We've now got to build a Linux (Ubuntu) version and we're getting a similar path problem. I tried fix-path but it doesn't seem to work on Linux. Are there any plans to extend it out to Linux ?

Thanks

Ian

**Comment by MonkeyChap** [comment]
Should have looked at the source code first ! There's an if statement in there detecting Darwin. I just commented it out in my local copy, and it fixed the path in Ubuntu.

[didn't fix the error I was getting though, so something else broken too].

**Comment by MonkeyChap** [comment]
Had to revisit this today. Seems Linux does have the same problem as Darwin. Could you add me to the contributors so I can alter the code to run the fix for Linux too ?  

Or failing that, could you change the if statement to:

```
if ((process.platform !== 'darwin') && (process.platform !== 'linux')){
		return;
	}
```

Ian

**Comment by kevva** [comment]
In what type of application are you using this?

**Comment by MonkeyChap** [comment]
It's an electron app that runs a python script. The script won't show up in the packaged app under Linux and Darwin unless I run fix-path. It's not a huge problem to adapt it locally if you want to keep it mac-only on github. I could even just do a manual path fix.
