### ISSUE TITLE
ES Module import error

### ISSUE THREAD

**Issue by ahmad-invozone** [sindresorhus/fix-path#16]
**Environment:** Node v14

There is an import error after upgrading to v4.

**ERROR:** : Must use import to load ES Module.

**Screenshot is also attached for reference:**
![image](https://user-images.githubusercontent.com/77004065/136019270-ea45c84b-f44b-4c13-abbf-08cf2f6c8a2d.png)

**Comment by sindresorhus** [comment]
Please read the release notes.

**Comment by kmturley** [comment]
You can use the previous version of the package:
```
npm install fix-path@v3.0.0
```
