### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by yask123** [sindresorhus/fix-path#7]
I got unexpected token error in fix-path code.

This is the content of fix-path:

```
'use strict';
module.exports = () => {
    const env = process.env;

    if (process.platform === 'darwin') {
        return env.SHELL || '/bin/bash';
    }

    if (process.platform === 'win32') {
        return env.COMSPEC || 'cmd.exe';
    }

    return env.SHELL || '/bin/sh';
}();
```

When I removed last `()` , it didn't give invalid syntax error.

What could be wrong?

I installed nodejs via brew
`$ node --version
v5.10.1`

**Comment by silverwind** [comment]
Not sure how this is related to this module, but you can't invoke a function declaration, you need to wrap it to create an expression, e.g. `(() => 1)()`.

**Comment by sindresorhus** [comment]
@yask123 Fixed in https://github.com/sindresorhus/default-shell/commit/d3e441382f0b95515dd208ca228ace817a3535a2. Just reinstall this module.

**Comment by silverwind** [comment]
Ah, the issue was in another module 👍 I wonder how that slipped through CI.

**Comment by sindresorhus** [comment]
@silverwind Somehow that syntax worked fine in Node.js 4.

**Comment by silverwind** [comment]
@sindresorhus yeah, looks like a v8 bug. Must've been fixed in 6.0.0 or earlier.

**Comment by silverwind** [comment]
Related: http://stackoverflow.com/questions/34589488/es6-immediately-invoked-arrow-function

**Comment by yask123** [comment]
That was quick! Thanks! 👍
